<!doctype html>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<#assign rootPath=springMacroRequestContext.contextPath />
<#-- jquery-3.6.0-->
<script src="${rootPath}/js/jquery-3.6.0.min.js"></script>
<!-- Bootstrap 5.1.3 CSS -->
<link rel="stylesheet" href="${rootPath}/css/bootstrap.min.css">
<script src="${rootPath}/js/bootstrap.bundle.min.js"></script>
<#-- jquery-confirm-3.3.4-->
<link rel="stylesheet" href="${rootPath}/css/jquery-confirm.min.css">
<script src="${rootPath}/js/jquery-confirm.min.js"></script>
<#-- toastr-2.1.4 訊息通知-->
<link rel="stylesheet" href="${rootPath}/css/toastr.min.css">
<script src="${rootPath}/js/toastr.min.js"></script>
